name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: check
      run: ls -la
    - name: Install compiler...
      run: sudo apt install gcc-arm-none-eabi
    - name: Cloning and building GTest...
      run: git clone https://github.com/google/googletest.git && cd googletest && mkdir build && cd build && cmake .. && sudo make install
    - name: check
      run: ls -la
    - name: building app in progress...
      run: make
    - name: building UT in progress...
      run: make test
    - name: running UT...
      run: ./gtest_run.sh
    - name: Install doxygen
      run: sudo apt-get install doxygen
    - name: building doc...
      run: make doc
      
